name: Build and Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Initialize and update submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run integration tests
      run: docker compose -f BTCPayServer.Plugins.IntegrationTests/docker-compose.yml run tests

    - name: Cleanup Docker containers
      if: always()
      run: docker compose -f BTCPayServer.Plugins.IntegrationTests/docker-compose.yml down -v
